### ISSUE TITLE
Dropdata outdated

### ISSUE THREAD

**Issue by m0ltay** [WFCD/warframe-drop-data#55]
### Warframe Drops Site Issue
---

**Summary (short):**
Database was last parsed on June 24th 

![db](https://user-images.githubusercontent.com/52664130/60820207-428f3980-a1a1-11e9-852e-312fb80c9b7f.JPG)

Cheers

**Comment by atomicptr** [comment]
Probably because the build fails https://travis-ci.com/WFCD/warframe-drop-data/builds/118208634#L968

**Comment by TobiTenno** [comment]
fixed the script

**Comment by atomicptr** [comment]
There is still a problem i guess, https://travis-ci.com/WFCD/warframe-drop-data/builds/118322879#L966

**Comment by TobiTenno** [comment]
i'll take a look

**Comment by yianniscy84** [comment]
Hi, There seems to still be a problem e.g. Wukong Prime does not appear in the API

**Comment by TobiTenno** [comment]
_sigh_

please read the comments when you comment on an issue.

**Comment by 4ndefined** [comment]
thanks for update

**Comment by TobiTenno** [comment]
should be fixed now
